// <auto-generated />
namespace ProjectWork.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_migration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_migration2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704171253120_initial_migration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
